baseurl = "https://abcstack.org"
languageCode = "en"
defaultContentLanguage = "en"
title = "ABCSTACK | Cloud Native Accelerator"
theme = "dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "ABCSTACK"
  # description = ""
  avatar = "/img/avatar.jpg"
  motto = "ABCSTACK"
  
  email = "docker2@163.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true
